import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "./components/header/Header";
import CarouselComponent from "./components/carousel";
import Blog from "./components/blog";
import NutritionInfo from "./components/nutritionInfo";
import Footer from "./components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>CPJ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />

        <CarouselComponent />
        <button className={styles.topOrderBtn}>Order Now</button>

        <div className={styles.container}>
          <div className={styles.subContainer}>
            <div className={styles.flex_div}>
              <div className={styles.image_container}>
                <Image
                  className={styles.logo}
                  src="/image8.png"
                  alt="image1"
                  width={600}
                  height={400}
                  layout="responsive"
                  objectFit="contain"
                  priority
                />
              </div>
              <div className={styles.text_container}>
                <div>
                  <p className={styles.desc}>
                    Stacked with protein, good fats and complex carbohydrates,
                    this shake is the perfect healthy breakfast alternative to
                    keep you full up till lunchtime
                  </p>
                  <p className={styles.desc}>
                    Its contains maca and cacao to help rid your body of pesky
                    free radicals. To top it off, beetroot is packed with
                    calcium, vitamin C, postassium and folic acid - a great way
                    to kick-start the morning.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <Blog />

        <NutritionInfo />

        <button className={styles.orderBtn}>Order Now</button>

        <Footer />
      </main>
    </>
  );
}
